/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/8PmdQ2cD7ju
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { CardContent, Card } from "@/components/ui/card"
import Link from "next/link"
import Image from "next/image"
import { JSX, SVGProps } from "react"


export default function Home() {
  return (
    <main key="1" className="flex flex-col items-center justify-center h-screen gap-12">
      <div className="flex items-center justify-center">
        <Image
            src="/1112c24ea6ca55155acbc72c9c0698cc.webp"
            alt="UEditor"
            width={128}
            height={128} />
      </div>
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <Link href="#">
          <Card className="hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors bg-black group rounded">
            <CardContent className="flex flex-col items-center justify-center p-6 space-y-2">
              <InfoIcon className="h-8 w-8 text-gray-500 dark:text-gray-400 group-active:text-gray-900 dark:group-active:text-gray-50" />
              <span className="text-sm font-medium group-active:font-bold group-active:text-gray-900 dark:group-active:text-gray-50">
                About
              </span>
            </CardContent>
          </Card>
        </Link>
        <Link href="#">
          <Card className="hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors bg-black group rounded">
            <CardContent className="flex flex-col items-center justify-center p-6 space-y-2">
              <DownloadIcon className="h-8 w-8 text-gray-500 dark:text-gray-400 group-active:text-gray-900 dark:group-active:text-gray-50" />
              <span className="text-sm font-medium group-active:font-bold group-active:text-gray-900 dark:group-active:text-gray-50">
                Install
              </span>
            </CardContent>
          </Card>
        </Link>
        <Link href="#">
          <Card className="hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors bg-black group rounded">
            <CardContent className="flex flex-col items-center justify-center p-6 space-y-2">
              <UsersIcon className="h-8 w-8 text-gray-500 dark:text-gray-400 group-active:text-gray-900 dark:group-active:text-gray-50" />
              <span className="text-sm font-medium group-active:font-bold group-active:text-gray-900 dark:group-active:text-gray-50">
                Account
              </span>
            </CardContent>
          </Card>
        </Link>
        <Link href="plugins">
          <Card className="hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors bg-black group rounded">
            <CardContent className="flex flex-col items-center justify-center p-6 space-y-2">
              <ShoppingBagIcon className="h-8 w-8 text-gray-500 dark:text-gray-400 group-active:text-gray-900 dark:group-active:text-gray-50" />
              <span className="text-sm font-medium group-active:font-bold group-active:text-gray-900 dark:group-active:text-gray-50">
                Store
              </span>
            </CardContent>
          </Card>
        </Link>
      </div>
    </main>
  )
}

function DownloadIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <polyline points="7 10 12 15 17 10" />
      <line x1="12" x2="12" y1="15" y2="3" />
    </svg>
  )
}


function InfoIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="M12 16v-4" />
      <path d="M12 8h.01" />
    </svg>
  )
}


function MountainIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}


function ShoppingBagIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M6 2 3 6v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6l-3-4Z" />
      <path d="M3 6h18" />
      <path d="M16 10a4 4 0 0 1-8 0" />
    </svg>
  )
}


function UsersIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
      <circle cx="9" cy="7" r="4" />
      <path d="M22 21v-2a4 4 0 0 0-3-3.87" />
      <path d="M16 3.13a4 4 0 0 1 0 7.75" />
    </svg>
  )
}
